#cloud-config

groups:
  - ubuntu: [root, sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - '---- BEGIN SSH2 PUBLIC KEY ----Comment: "rsa-key-20211207"AAAAB3NzaC1yc2EAAAADAQABAAABAQCZcIP9WaaDVjI+gVodv3mrqU0pXsosshqvvd+zTWNLT50IwGbOzCWo7R3pmq83zJJ+VedUUK0LFE9HezALiatkkCXDTqWAC4/XSHKbuH4HdQrdd1wkw2gZcHKv6o5pV7deESseMf7g2I+aEJ58XvvNRWuFaifKHp7x/pl9XqM3axXpVgcpQTHb+cqe5pEenUALrkK8OiDv2tBlmu4EF2XMvMb0pd/jRxS5C5+p75u5u6YxfqV1W2ZvOnK8ntgiZ9xsgf1Lo52vRCLnEcTsr9e3NhI0MzxHvQG2lyhqkO9/uZF+vqIx37ZK7EVNSrUU9fS019FtNArX7IDtDwNN/jNB---- END SSH2 PUBLIC KEY ----'
